### ISSUE TITLE
Brand discussion

### ISSUE THREAD

**Issue by mirkobrombin** [mirkobrombin/pagekit#20]
Pagekit is owned by YOOtheme. The name, the brand, the project itself are of their respective owners.

This fork needs an alternative marketplace as some additional features will be available in the future. Furthermore it is not given to know if the official project will be maintained and if more frequent updates will be introduced.

Official Pagekit (today) suffers from several vulnerabilities and lacks essential features for developers.

The purpose of this fork (was) was to make up for these shortcomings to a small extent. Today the goal has changed and we have chosen to build our own path, regardless of the future of the official version.

This fork is about to change its name to **bis[ku]it** (formally biskuit).

The MIT license will be maintained, the YOOtheme credits will be maintained, side by side with ours (in accordance with the license).

However it is important to know that the general copyright will be changed, exempting YOOtheme from any liability (in accordance with the license).

**Comment by hersel91** [comment]
We suggest this logo by Miki Locuratolo
[biskuit.pdf](https://github.com/mirkobrombin/pagekit/files/3936249/biskuit.pdf)

**Comment by hersel91** [comment]
Edit
![biskuit2](https://user-images.githubusercontent.com/11424277/70390075-cb680680-19c7-11ea-95c5-5d683f6882ee.png)

**Comment by mirkobrombin** [comment]
## Why bis[ku]it
The name bis[ku]it (biskuit) means biscuit in Indonesian (maybe even in German) and remembers the cookies, used to keep the sessions active on the CMS.

Second, biskuit is composed: bis, ku, it. It is a simple word game:
* In Italy (probably elsewhere) when a dish is good, it is customary to say "Let's do the bis" means: let's do another round. This is the bis of pagekit.
* [ku]it can be decomposed to form the word uikit, the framework used by pagekit and developed by yootheme.
